# Generated by Django 5.2.17 on 2026-09-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(blank=True, max_length=100)),
                ('policyholder_name', models.CharField(blank=True, max_length=200)),
                ('effective_start_date', models.DateField(blank=True, null=True)),
                ('effective_end_date', models.DateField(blank=True, null=True)),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('incident_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('claimant', models.CharField(blank=True, max_length=200)),
                ('third_parties', models.TextField(blank=True)),
                ('contact_details', models.CharField(blank=True, max_length=300)),
                ('asset_type', models.CharField(blank=True, max_length=100)),
                ('asset_id', models.CharField(blank=True, max_length=100)),
                ('estimated_damage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('claim_type', models.CharField(blank=True, max_length=100)),
                ('attachments', models.TextField(blank=True)),
                ('initial_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('missing_fields', models.JSONField(default=list)),
                ('inconsistencies', models.JSONField(default=list)),
                ('recommended_route', models.CharField(blank=True, max_length=100)),
                ('reasoning', models.TextField(blank=True)),
                ('investigation_flag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
